export type Product = {
  id: string;
  name: string;
  collection: "private" | "sapphire" | "essence" | "atelier" | "signature" | "essentials";
  category: string;
  price: number;
  originalPrice?: number;
  image: string;
  images: string[];
  lengths: string[];
  colors: string[];
  density: string;
  texture: string;
  capSize: string[];
  description: string;
  longDescription: string;
  details: string[];
  lengthPrices?: Record<string, number>;
  closureOptions?: Array<{
    type: string;
    lengthPrices: Record<string, number>;
  }>;
  modelSpecs?: {
    closureType?: string;
    texture?: string;
    length?: string;
    density?: string;
    color?: string;
    styling?: string;
  };
  inStock: boolean;
  stockCount: number;
  featured?: boolean;
  bestseller?: boolean;
};

export const collections = [
  {
    slug: "private",
    name: "Private Collection",
    subtitle: "Raw Reserve",
    tagline: "Reserved for the Exceptional.",
    description:
      "The rarest single-donor hair, preserved in its purest, most untouched form.",
    poeticText: [
      "Exceptionally rare.",
      "Intentionally limited.",
      "Privately acquired.",
      "An heirloom in its truest form.",
    ],
    accent: "Lifetime",
    years: "LIFETIME",
    color: "#2B1B12",
    image: "/products/private_collection.PNG",
    video: "/private.MP4",
    priceFrom: 1850000,
  },
  {
    slug: "sapphire",
    name: "Sapphire Collection",
    subtitle: "Sapphire",
    tagline: "SAPPHIRE COLLECTION",
    description:
      "Meticulously selected. Expertly finished to HAIR OVEN standards. Quietly distinctive.",
    poeticText: [
      "Meticulously selected.",
      "Expertly finished to HAIR OVEN standards.",
      "Quietly distinctive.",
    ],
    accent: "2 to 3+ Years",
    years: "2 to 3+ YEARS",
    color: "#3D2314",
    image: "/products/signature_collection.jpg",
    priceFrom: 285000,
  },
  {
    slug: "essence",
    name: "Essence Collection",
    subtitle: "Essence",
    tagline: "EVERYDAY, ELEVATED.",
    description:
      "Beautifully selected hair, refined for effortless everyday wear. Luxury, made effortless.",
    poeticText: ["Everyday, elevated.", "Luxury, made effortless."],
    accent: "Everyday Versatile",
    years: "12 to 18 MONTHS",
    color: "#57534E",
    image: "/products/essential_collection.jpeg",
    priceFrom: 145000,
  },
  {
    slug: "atelier",
    name: "Atelier Collection",
    subtitle: "Bespoke Atelier",
    tagline: "MADE FOR ONE.",
    description:
      "A private commission created around the individual. Custom cranial mapping, density and Oven Veil™ architecture.",
    poeticText: ["Made for one.", "Custom architectural commission."],
    accent: "Bespoke Masterwork",
    years: "BESPOKE",
    color: "#2B1B12",
    image: "/products/ATELIER.PNG",
    priceFrom: 1850000,
  },
] as const;

export const products: Product[] = [
  {
    id: "signature-adewunmi",
    name: "The Adewunmi",
    collection: "signature",
    category: "Wigs",
    price: 1600000,
    image: "/products/ADEWUNMI.jpeg",
    images: ["/products/ADEWUNMI.jpeg"],
    lengths: ['26"', '28"', '30"'],
    lengthPrices: {
      '26"': 1600000,
      '28"': 1750000,
      '30"': 1900000,
    },
    closureOptions: [
      {
        type: "2x6 Lace Closure",
        lengthPrices: {
          '26"': 1600000,
          '28"': 1750000,
          '30"': 1900000,
        },
      },
      {
        type: "6x6 HD Lace Closure",
        lengthPrices: {
          '26"': 1900000,
          '28"': 2150000,
          '30"': 2300000,
        },
      },
      {
        type: "13x4 HD Frontal",
        lengthPrices: {
          '26"': 2250000,
          '28"': 2350000,
          '30"': 2550000,
        },
      },
    ],
    colors: ["Tangerine Dream (High-Saturation Vivid Orange)"],
    density: "Full Precision Density",
    texture: "Sleek Precision Cut",
    capSize: ["S", "M", "L", "XL"],
    description:
      "Make an unforgettable statement with our Tangerine Dream unit. This ultra-vibrant, vivid orange hair commands attention with high-saturation color.",
    longDescription:
      "Make an unforgettable statement with our Tangerine Dream unit. This ultra-vibrant, vivid orange hair commands attention with high-saturation color. Perfect for high-fashion photoshoots, exclusive events, or a complete style transformation.",
    details: [
      "Premium human hair",
      "Sleek, precision-cut bob",
      "Natural-looking movement and lustre",
      "High-saturation Tangerine Dream color",
      "Available in 2x6, 6x6 HD Lace, and 13x4 HD Frontal options",
      "Handcrafted preorder commission",
    ],
    modelSpecs: {
      closureType: "2x6 / 6x6 HD Lace Closure or 13x4 HD Frontal",
      texture: "100% Premium Human Hair (Sleek Precision Cut)",
      length: '26" - 30"',
      density: "Full Precision Density",
      color: "Tangerine Dream Vivid Orange",
      styling: "Sleek Precision-Cut Bob",
    },
    inStock: true,
    stockCount: 3,
    featured: true,
  },
  {
    id: "signature-argentine-bob",
    name: "The Argentine Bob",
    collection: "signature",
    category: "Wigs",
    price: 299000,
    originalPrice: 320000,
    image: "/products/THE_ARGENTINE_BOB.PNG",
    images: ["/products/THE_ARGENTINE_BOB.PNG"],
    lengths: ['6"', '8"', '10"', '12"'],
    lengthPrices: {
      '6"': 299000,
      '8"': 320000,
      '10"': 350000,
      '12"': 385000,
    },
    colors: ["Glass-Smooth Natural Black"],
    density: "Full, Natural-Looking Density",
    texture: "Silky Straight",
    capSize: ["S", "M", "L", "XL"],
    description:
      "A precisely crafted, ultra-sleek bob defined by its clean silhouette, immaculate movement, and naturally lustrous finish.",
    longDescription:
      "A precisely crafted, ultra-sleek bob defined by its clean silhouette, immaculate movement, and naturally lustrous finish. Designed for effortless sophistication, The Bob is cut to create a sharp yet feminine silhouette: minimal in expression, exceptional in detail.",
    details: [
      "Style: Sleek Blunt Bob",
      "Length: Chin-length",
      "Texture: Silky Straight",
      "Finish: High-shine, glass-smooth",
      "Density: Full, natural-looking density",
      "Appearance: Soft, polished, and exceptionally refined",
      "Collection: Signature Collection",
    ],
    modelSpecs: {
      closureType: "Customised Thin HD Lace Closure 5x5",
      texture: "100% Raw Silky Straight Hair",
      length: '10"',
      density: "Full 250g",
      color: "Glass-Smooth Natural Black",
      styling: "Middle Parting",
    },
    inStock: true,
    stockCount: 2,
    featured: true,
  },
  {
    id: "signature-caramel-wave-24",
    name: "The Signature Caramel Wave",
    collection: "signature",
    category: "Wigs",
    price: 1550000,
    image: "/products/caramel-wave.jpeg",
    images: ["/products/caramel-wave.jpeg"],
    lengths: ['18"', '20"', '22"', '24"'],
    lengthPrices: {
      '18"': 1550000,
      '20"': 1700000,
      '22"': 2100000,
      '24"': 2450000,
    },
    colors: ["Espresso Brown with Caramel Dimension"],
    density: "385g",
    texture: "Soft, Sculpted Waves",
    capSize: ["S", "M", "L"],
    description:
      "A masterclass in dimensional artistry, The Caramel Wave introduces warm, hand-painted golden highlights over a deep espresso foundation.",
    longDescription:
      "A masterclass in dimensional artistry, The Caramel Wave introduces warm, hand-painted golden highlights over a deep espresso foundation. Designed to frame the face with radiant warmth, it delivers dynamic movement and unmistakable allure.",
    details: [
      "Espresso Brown with Caramel Dimension",
      "Soft, Sculpted Waves",
      "Defined Centre Part",
      "Density: 385g",
      "Silky, Gloss-Luminous & Polished",
      "Full-Length with Cascading Movement",
      "Sophisticated, Timeless & Effortlessly Glamorous",
    ],
    modelSpecs: {
      closureType: "Customised Thin HD Lace Closure 5x5",
      texture: "Soft, Sculpted Waves",
      length: '24"',
      density: "385g",
      color: "Espresso Brown with Caramel Dimension",
      styling: "Centre Parting",
    },
    inStock: true,
    stockCount: 1,
    featured: true,
    bestseller: true,
  },
  {
    id: "signature-velmorea-24",
    name: "The Velmoréa",
    collection: "signature",
    category: "Wigs",
    price: 1400000,
    image: "/products/velmorea.jpeg",
    images: ["/products/velmorea.jpeg"],
    lengths: ['20"', '22"', '24"'],
    lengthPrices: {
      '20"': 1400000,
      '22"': 1550000,
      '24"': 1700000,
    },
    colors: ["Rich Espresso-Black Finish"],
    density: "385g",
    texture: "Sleek Body with Sculpted Waves",
    capSize: ["S", "M", "L"],
    description:
      "A study in polished glamour, The Velmoréa is designed for an unmistakably luxurious presence.",
    longDescription:
      "A study in polished glamour, The Velmoréa is designed for an unmistakably luxurious presence. Engineered to capture effortless sophistication without appearing overworked, this unit transitions seamlessly from high-profile occasions to modern statement dressing.",
    details: [
      "Sleek body with sculpted waves",
      "Rich espresso-black finish",
      "Refined centre-part styling",
      "Density: 385g",
      "Signature Collection",
      "Fluid, Tangle-Free Movement with High Silhouette Retention",
    ],
    modelSpecs: {
      closureType: "Customised Thin HD Lace Closure 5x5",
      texture: "Sleek Body with Sculpted Waves",
      length: '24"',
      density: "385g",
      color: "Rich Espresso-Black Finish",
      styling: "Centre Parting",
    },
    inStock: true,
    stockCount: 3,
    featured: true,
    bestseller: true,
  },
  {
    id: "signature-adunni-26",
    name: "The Àdunnī",
    collection: "signature",
    category: "Wigs",
    price: 1700000,
    image: "/products/adunni.png",
    images: ["/products/adunni.png"],
    lengths: ['20"', '22"', '24"', '26"', '28"'],
    lengthPrices: {
      '20"': 1700000,
      '22"': 2100000,
      '24"': 2450000,
      '26"': 2600000,
      '28"': 2800000,
    },
    colors: ["Deep Natural-Black Finish"],
    density: "500g",
    texture: "Defined Voluminous Curls",
    capSize: ["S", "M", "L"],
    description:
      "A dramatic expression of natural texture and refined volume, The Àdunnī is designed for those who want presence without compromise.",
    longDescription:
      "A dramatic expression of natural texture and refined volume, The Àdunnī is designed for those who want presence without compromise.",
    details: [
      "Luxuriously long length",
      "Defined, voluminous curls",
      "Deep natural-black finish",
      "Density: 500g",
      "Softly framed hairline",
      "Rich, glossy texture",
      "Statement Signature Collection piece",
    ],
    modelSpecs: {
      closureType: "Customised Thin HD Lace Closure 5x5",
      texture: "Defined Voluminous Curls",
      length: '28"',
      density: "500g",
      color: "Deep Natural-Black Finish",
      styling: "Natural Parting",
    },
    inStock: true,
    stockCount: 4,
    featured: true,
  },
  {
    id: "signature-aurelia-barrel-curl-24",
    name: "Aurelia Barrel Curl",
    collection: "signature",
    category: "Wigs",
    price: 355000,
    originalPrice: 390000,
    image: "/products/aurelia-barrel-curl.jpeg",
    images: ["/products/aurelia-barrel-curl.jpeg"],
    lengths: ['18"', '20"', '22"', '24"'],
    colors: ["Precision Honey Brown & Chestnut Highlights"],
    density: "250%",
    texture: "Defined Barrel Curls",
    capSize: ["S", "M", "L"],
    description:
      "Elevate your style with this high-end, statement-making lace front wig. Designed for a flawless, natural appearance.",
    longDescription:
      "Elevate your style with this high-end, statement-making lace front wig. Designed for a flawless, natural appearance, it is the ultimate protective style for photoshoots, special events, or everyday glam.",
    details: [
      "Seamlessly blends into any skin tone.",
      "Defined barrel curls that hold shape and movement without weighing down.",
      "Flexible parting versatility.",
      "Precision coloring meets defined volume for an uncompromised luxury look.",
    ],
    inStock: true,
    stockCount: 2,
    featured: true,
  },
  {
    id: "signature-honey-ash-bronzed-wave-24",
    name: "The Honey-Ash Bronzed Wave",
    collection: "signature",
    category: "Wigs",
    price: 385000,
    originalPrice: 420000,
    image: "/products/honey-ash-bronzed-wave.jpeg",
    images: ["/products/honey-ash-bronzed-wave.jpeg"],
    lengths: ['20"', '22"', '24"', '26"'],
    colors: ["Warm Honey & Ash Blonde Highlights"],
    density: "250%",
    texture: "Hollywood S-Waves",
    capSize: ["S", "M", "L"],
    description:
      "A seamless blend of warm honey and ash blonde tones, styled in effortless Hollywood waves.",
    longDescription:
      "A seamless blend of warm honey and ash blonde tones, styled in effortless Hollywood waves. Masterfully toned ash and golden-honey blonde highlights woven over a dark root for maximum depth.",
    details: [
      "Dimensional sophistication",
      "Masterfully toned ash and golden-honey blonde highlights woven over a dark root for maximum depth.",
      "Long, luxurious length",
      "Soft, cascading S-waves engineered to maintain bounce, body, and high-shine fluid movement.",
      "Private Signature Collection",
    ],
    inStock: true,
    stockCount: 2,
    featured: true,
  },
  {
    id: "private-bone-straight-20",
    name: "Raw Bone Straight 20″",
    collection: "private",
    category: "Wigs",
    price: 485000,
    image: "/products/editorial-model.jpg",
    images: [
      "/products/editorial-model.jpg",
      "/products/signature_page.jpeg",
    ],
    lengths: ['14"', '16"', '18"', '20"', '22"', '24"'],
    colors: ["Natural Black", "Natural Brown", "Jet Black"],
    density: "250%",
    texture: "Bone Straight",
    capSize: ["S", "M", "L"],
    description: "Single-donor raw hair, completely unprocessed. Cuticles intact, aligned.",
    longDescription:
      "Our most exclusive offering. Single-donor raw hair that has never been chemically processed. Each strand retains its natural cuticle alignment for unparalleled silkiness, movement and longevity. Investment-grade hair that becomes more beautiful with time.",
    details: ["Single donor", "Unprocessed", "Intact cuticles", "Oven Veil™ lace", "Lifetime with care"],
    inStock: true,
    stockCount: 5,
    featured: true,
  },
  {
    id: "private-body-wave-22",
    name: "Raw Body Wave 22″",
    collection: "private",
    category: "Wigs",
    price: 520000,
    image: "/products/signature_page.jpeg",
    images: [
      "/products/signature_page.jpeg",
      "/products/editorial-model-2.jpg",
    ],
    lengths: ['18"', '20"', '22"', '24"'],
    colors: ["Natural Black", "Natural Brown"],
    density: "250%",
    texture: "Body Wave",
    capSize: ["M", "L"],
    description: "Voluminous raw body wave with natural luster.",
    longDescription: "Oceanic waves crafted from unprocessed single-donor hair. Bouncy, full and eternally elegant.",
    details: ["Raw single-donor", "Natural wave pattern", "High density"],
    inStock: true,
    stockCount: 4,
    featured: true,
  },
  {
    id: "signature-the-essential",
    name: "The Essential",
    collection: "signature",
    category: "Wigs",
    price: 1595000,
    image: "/products/another_one_essential.jpeg",
    images: ["/products/another_one_essential.jpeg", "/products/essential.jpeg", "/products/essential_collection.jpeg"],
    lengths: ['24"', '26"', '28"', '30"'],
    lengthPrices: {
      '24"': 1595000,
      '26"': 1650000,
      '28"': 1850000,
      '30"': 1999999,
    },
    closureOptions: [
      {
        type: "6x6 HD Lace Closure",
        lengthPrices: {
          '24"': 1595000,
          '26"': 1650000,
          '28"': 1850000,
          '30"': 1999999,
        },
      },
    ],
    colors: ["Honey Blonde with Dark Shadow Root"],
    density: "Full Precision Volume (385g)",
    texture: "Sculpted Waves",
    capSize: ["S", "M", "L", "XL"],
    description:
      "A masterpiece of quiet luxury, The Essential presents voluminous sculpted waves with a dark shadow root, seamless blending, and immaculate bounce.",
    longDescription:
      "A masterpiece of quiet luxury, The Essential presents voluminous sculpted waves with a dark shadow root, seamless blending, and immaculate bounce. Cut from premium human hair and paired with a 6x6 HD lace closure, this unit delivers natural hairline blending and high-end movement.",
    details: [
      "Style: Voluminous Sculpted Waves",
      "Closure: 6x6 HD Lace Closure",
      "Texture: Sculpted Waves",
      "Density: Full Precision Volume (385g)",
      "Collection: Signature Collection",
      "Available Lengths: 24″, 26″, 28″, 30″",
    ],
    modelSpecs: {
      closureType: "6x6 HD Lace Closure",
      texture: "100% Premium Human Hair (Sculpted Waves)",
      length: '24" - 30"',
      density: "Full Precision Volume (385g)",
      color: "Honey Blonde with Dark Shadow Root",
      styling: "Defined Side Parting",
    },
    inStock: true,
    stockCount: 2,
    featured: true,
  },
  {
    id: "signature-precision-bob",
    name: "The Essential Precision Bob",
    collection: "signature",
    category: "Wigs",
    price: 350000,
    image: "/products/another_essential.jpeg",
    images: ["/products/another_essential.jpeg", "/products/THE_ARGENTINE_BOB.PNG"],
    lengths: ['6"', '8"', '10"'],
    lengthPrices: {
      '6"': 350000,
      '8"': 380000,
      '10"': 420000,
    },
    closureOptions: [
      {
        type: "Thin HD Lace Closure",
        lengthPrices: {
          '6"': 350000,
          '8"': 380000,
          '10"': 420000,
        },
      },
    ],
    colors: ["Honey Blonde Precision Finish"],
    density: "Full Precision Density",
    texture: "Sleek Precision Cut",
    capSize: ["S", "M", "L", "XL"],
    description:
      "Designed for the woman who values quiet distinction, this timeless silhouette transitions seamlessly from day to evening, offering exceptional versatility without compromising its refined character.",
    longDescription:
      "Designed for the woman who values quiet distinction, this timeless silhouette transitions seamlessly from day to evening, offering exceptional versatility without compromising its refined character.",
    details: [
      "Premium human hair",
      "Sleek, precision-cut bob",
      "Natural-looking movement and lustre",
      "Lightweight, comfortable construction",
      "Designed for effortless styling and longevity",
    ],
    modelSpecs: {
      closureType: "Thin HD Lace Closure",
      texture: "100% Premium Human Hair (Sleek Precision Cut)",
      length: '6" - 10"',
      density: "Full Precision Density",
      color: "Honey Blonde Precision Finish",
      styling: "Middle Parting Bob",
    },
    inStock: true,
    stockCount: 3,
    featured: true,
  },
  {
    id: "essentials-wave-14",
    name: "Essentials Loose Wave 14″",
    collection: "essentials",
    category: "Wigs",
    price: 145000,
    image: "/products/essentials.jpg",
    images: [
      "/products/essentials.jpg",
      "/products/essential_collection.jpeg",
    ],
    lengths: ['12"', '14"', '16"', '18"'],
    colors: ["Natural Black", "Brown", "Blonde"],
    density: "180%",
    texture: "Loose Wave",
    capSize: ["S", "M", "L"],
    description: "Dependable everyday beauty. Soft waves, effortless rotation.",
    longDescription: "Perfect for daily wear. Beautiful, resilient and crafted for versatility.",
    details: ["Human hair", "Everyday density", "Easy maintenance"],
    inStock: true,
    stockCount: 6,
  },
  {
    id: "essentials-bob-10",
    name: "Essentials Blunt Bob 10″",
    collection: "essentials",
    category: "Wigs",
    price: 165000,
    image: "/products/another_essential.jpeg",
    images: [
      "/products/another_essential.jpeg",
      "/products/essentials.jpg",
    ],
    lengths: ['8"', '10"', '12"', '14"'],
    colors: ["Natural Black", "Jet Black", "Wine"],
    density: "200%",
    texture: "Blunt Cut Straight",
    capSize: ["S", "M"],
    description: "Precision bob. Editorial edge for the modern woman.",
    longDescription: "A sharp, confident silhouette. Cut and crafted for polish.",
    details: ["Blunt cut", "Natural parting", "Lightweight cap"],
    inStock: true,
    stockCount: 3,
  },
  {
    id: "closure-oven-veil",
    name: "Oven Veil™ 13×6 HD Frontal",
    collection: "essentials",
    category: "Closures & Frontals",
    price: 95000,
    image: "/products/essential.jpeg",
    images: [
      "/products/essential.jpeg",
      "/products/another_one_essential.jpeg",
    ],
    lengths: ['12"', '14"', '16"'],
    colors: ["Transparent", "Medium Brown", "Dark Brown"],
    density: "N/A",
    texture: "Ultra-sheer lace",
    capSize: ["One Size"],
    description: "Our proprietary ultra-sheer lace. The invisible hairline.",
    longDescription: "Mimics skin texture. Melts seamlessly. Truly undetectable.",
    details: ["Ultra-sheer", "Pre-plucked", "Bleached knots"],
    inStock: true,
    stockCount: 4,
    featured: true,
  },
  {
    id: "bundle-raw-3",
    name: "Raw Bundles Trio (18″–22″)",
    collection: "private",
    category: "Bundles",
    price: 385000,
    image: "/products/editorial-model-2.jpg",
    images: ["/products/editorial-model-2.jpg"],
    lengths: ['18"', '20"', '22"'],
    colors: ["Natural Black"],
    density: "Full 300g",
    texture: "Natural Single Donor Wave",
    capSize: ["N/A"],
    description: "Three raw single-donor bundles selected in the most exacting manner.",
    longDescription: "Three raw single-donor bundles selected in the most exacting manner for absolute cuticle alignment, silkiness, and weightless swing.",
    details: ["3 single-donor raw bundles", "Unprocessed intact cuticles", "Heirloom grade"],
    inStock: true,
    stockCount: 5,
    featured: true,
  },
  {
    id: "extensions-raw-clipins",
    name: "Raw Reserve Seamless Clip-Ins",
    collection: "private",
    category: "Hair Extensions",
    price: 320000,
    image: "/products/editorial-styling.jpg",
    images: ["/products/editorial-styling.jpg"],
    lengths: ['18"', '20"', '22"', '24"'],
    colors: ["Natural Black", "Espresso"],
    density: "220g",
    texture: "Raw Straight",
    capSize: ["N/A"],
    description: "Instant volume and length crafted from our rarest single-donor raw reserves.",
    longDescription: "Instant volume and length crafted from our rarest single-donor raw reserves. Seamless polyurethane tracks lay completely flat against your scalp.",
    details: ["Single donor raw hair", "Ultra-thin polyurethane seamless tracks", "7 pieces per set"],
    inStock: true,
    stockCount: 4,
    featured: true,
  },
  {
    id: "bespoke-bridal-heirloom",
    name: "Bridal Heirloom Commission",
    collection: "private",
    category: "Bespoke Hair",
    price: 2450000,
    image: "/products/bridal_consultation.jpeg",
    images: ["/products/bridal_consultation.jpeg", "/products/bridal_image1.jpeg", "/products/bridal_image2.jpeg"],
    lengths: ['24"', '26"', '28"', '30"'],
    colors: ["Custom Tone & Dimensional Match"],
    density: "450g",
    texture: "Sculpted Waves",
    capSize: ["S", "M", "L", "Custom 3D"],
    description: "A singular creation crafted directly with Founder Hannah for your wedding weekend.",
    longDescription: "A singular creation crafted directly with Founder Hannah for your wedding weekend. Built with ultra-sheer Oven Veil HD lace, matching single-donor raw hair, and custom cranial molding.",
    details: ["Direct consultation with Founder Hannah", "3D cranial measurement architecture", "100% creditable consultation deposit"],
    inStock: true,
    stockCount: 2,
    featured: true,
  },
  {
    id: "signature-bundles-trio",
    name: "Signature Raw Bundles Set",
    collection: "signature",
    category: "Bundles",
    price: 295000,
    image: "/products/signature_collection.jpeg",
    images: ["/products/signature_collection.jpeg"],
    lengths: ['16"', '18"', '20"'],
    colors: ["Natural Black"],
    density: "300g",
    texture: "Soft Natural Body",
    capSize: ["N/A"],
    description: "Refined through meticulous selection and finished to the exacting standards of HAIR OVEN.",
    longDescription: "Refined through meticulous selection and finished to the exacting standards of HAIR OVEN. Quietly distinctive bundles.",
    details: ["Signature raw hair", "High silhouette retention", "Double drawn weight"],
    inStock: true,
    stockCount: 4,
  },
  {
    id: "signature-tapeins",
    name: "Signature Seamless Tape-Ins",
    collection: "signature",
    category: "Hair Extensions",
    price: 265000,
    image: "/products/editorial-blowdry.jpg",
    images: ["/products/editorial-blowdry.jpg"],
    lengths: ['18"', '20"', '22"'],
    colors: ["Natural Black", "Honey Ash"],
    density: "150g",
    texture: "Silky Straight",
    capSize: ["N/A"],
    description: "Lightweight medical-grade adhesive tape-ins for invisible integration.",
    longDescription: "Lightweight medical-grade adhesive tape-ins for invisible integration.",
    details: ["40 tapes per pack", "Reusable up to 3 installs", "Signature cuticle integrity"],
    inStock: true,
    stockCount: 3,
  },
  {
    id: "signature-bespoke-atelier",
    name: "Bespoke Atelier Unit",
    collection: "signature",
    category: "Bespoke Hair",
    price: 1850000,
    image: "/products/ATELIER.PNG",
    images: ["/products/ATELIER.PNG"],
    lengths: ['22"', '24"', '26"'],
    colors: ["Custom Color Blend"],
    density: "380g",
    texture: "Custom Silhouette",
    capSize: ["S", "M", "L", "Custom"],
    description: "Custom hand-tied atelier unit tailored around your exact facial structure.",
    longDescription: "Custom hand-tied atelier unit tailored around your exact facial structure.",
    details: ["Atelier Senior Team fitting", "Oven Veil HD lace base"],
    inStock: true,
    stockCount: 2,
    featured: true,
  },
  {
    id: "essentials-bundles-trio",
    name: "Essentials Bundles Pack (14″–18″)",
    collection: "essentials",
    category: "Bundles",
    price: 185000,
    image: "/products/essential_collection.jpeg",
    images: ["/products/essential_collection.jpeg"],
    lengths: ['14"', '16"', '18"'],
    colors: ["Natural Black"],
    density: "250g",
    texture: "Soft Natural Wave",
    capSize: ["N/A"],
    description: "Beautifully selected hair, refined for effortless everyday wear.",
    longDescription: "Beautifully selected hair, refined for effortless everyday wear. Luxury, made effortless.",
    details: ["3 bundles pack", "Everyday versatile", "Easy styling"],
    inStock: true,
    stockCount: 5,
  },
  {
    id: "essentials-clipins",
    name: "Essentials Volume Clip-Ins",
    collection: "essentials",
    category: "Hair Extensions",
    price: 165000,
    image: "/products/another_essential.jpeg",
    images: ["/products/another_essential.jpeg"],
    lengths: ['16"', '18"', '20"'],
    colors: ["Natural Black", "Brown"],
    density: "160g",
    texture: "Straight",
    capSize: ["N/A"],
    description: "Effortless everyday clip-in extension set for instant fullness.",
    longDescription: "Effortless everyday clip-in extension set for instant fullness.",
    details: ["7 piece set", "Lightweight clips", "Daily wear"],
    inStock: true,
    stockCount: 4,
  },
  {
    id: "private-oven-veil-closure",
    name: "Raw Reserve 5×5 HD Closure",
    collection: "private",
    category: "Closures & Frontals",
    price: 175000,
    image: "/products/honey-ash-bronzed-wave.jpeg",
    images: ["/products/honey-ash-bronzed-wave.jpeg"],
    lengths: ['16"', '18"', '20"'],
    colors: ["Natural Black", "Transparent HD"],
    density: "N/A",
    texture: "Raw Straight",
    capSize: ["One Size"],
    description: "Single-donor raw hair paired with invisible Oven Veil HD lace.",
    longDescription: "Single-donor raw hair paired with invisible Oven Veil HD lace.",
    details: ["Ultra sheer HD lace", "Pre-plucked hairline", "Single donor strands"],
    inStock: true,
    stockCount: 3,
  },
  {
    id: "signature-hd-frontal",
    name: "Signature 13×4 HD Frontal",
    collection: "signature",
    category: "Closures & Frontals",
    price: 135000,
    image: "/products/velmorea.jpeg",
    images: ["/products/velmorea.jpeg"],
    lengths: ['16"', '18"', '20"'],
    colors: ["Natural Black"],
    density: "N/A",
    texture: "Body Wave",
    capSize: ["One Size"],
    description: "High-definition lace frontal providing ear-to-ear parting freedom.",
    longDescription: "High-definition lace frontal providing ear-to-ear parting freedom.",
    details: ["13x4 HD ear-to-ear", "Bleached knots", "Natural density"],
    inStock: true,
    stockCount: 4,
  },
];

export const testimonials = [
  {
    name: "Amara O.",
    location: "Lagos, NG",
    text: "The Private Collection is unlike anything I have owned. Three years in, no tangling at all, it still flows like brand new hair. Worth every single kobo.",
    product: "Raw Bone Straight 20″",
    rating: 5,
  },
  {
    name: "Zainab A.",
    location: "London, UK",
    text: "My hairstylist asked where I got this unit because the Oven Veil lace literally melted into my scalp without heavy bleaching. Truly elite master craftsmanship.",
    product: "Oven Veil™ Frontal",
    rating: 5,
  },
  {
    name: "Dr. Kemi A.",
    location: "Abuja, NG",
    text: "Signature Caramel Wave survived humid outdoor weddings, long flights, and daily styling without losing its pattern or body. Hair Oven never disappoints.",
    product: "The Signature Caramel Wave",
    rating: 5,
  },
  {
    name: "Ngozi E.",
    location: "Port Harcourt, NG",
    text: "I wore The Adewunmi unit for an event and everyone kept asking if it was my natural hair silk-pressed. Incredible density, soft finish, and zero shedding.",
    product: "The Adewunmi",
    rating: 5,
  },
];

export const craftsmanship = [
  { title: "Donor selection", desc: "Single-donor sourcing. Consistency from root to tip." },
  { title: "Cuticle alignment", desc: "Intact, aligned cuticles for silkiness and longevity." },
  { title: "Density", desc: "Up to 250% density. Full without bulk." },
  { title: "Movement", desc: "Natural swing. Hair that behaves like hair." },
  { title: "Construction", desc: "Hand-tied, ventilated, balanced." },
  { title: "Longevity", desc: "Years, not months. Heirloom-grade." },
  { title: "Quality control", desc: "Inspected strand by strand before dispatch." },
];

export const ovenVeilSteps = [
  { k: "01", t: "Texture", d: "Ultra-sheer Swiss lace mimicking natural skin pores." },
  { k: "02", t: "Construction", d: "Hand-ventilated, single-knotted for realism." },
  { k: "03", t: "Hairline", d: "Pre-plucked, micro-bleached. No harsh lines." },
  { k: "04", t: "Fit", d: "Ear-to-ear 13×6 with elastic balance." },
  { k: "05", t: "Result", d: "Melts. Disappears. Becomes you." },
];
